name = "danscarlot-api"
main = "worker.ts"
compatibility_date = "2025-02-07"
workers_dev = false

routes = [
  { pattern = "api.danscarlot.turneratlanta.com/api/*", zone_name = "turneratlanta.com" }
]

[durable_objects]
bindings = [
  { name = "CAR_STORE", class_name = "CarStore" }
]

[migrations]
[[migrations]]
tag = "v1"
new_classes = ["CarStore"]
